// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/finance.proto

package finance_v1





// 以下为消息类型定义（简化版，实际应由 protoc-gen-go 生成）
type GetMonthlyProfitLossRequest struct {
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Year     int32  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month    int32  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
}

func (x *GetMonthlyProfitLossRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetMonthlyProfitLossRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetMonthlyProfitLossRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type GetMonthlyProfitLossResponse struct {
	Data *MonthlyProfitLoss `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMonthlyProfitLossResponse) GetData() *MonthlyProfitLoss {
	if x != nil {
		return x.Data
	}
	return nil
}

type MonthlyProfitLoss struct {
	TenantId               string  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Year                   int32   `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month                  int32   `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	TotalRevenue           float64 `protobuf:"fixed64,4,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	SalesRevenue           float64 `protobuf:"fixed64,5,opt,name=sales_revenue,json=salesRevenue,proto3" json:"sales_revenue,omitempty"`
	ServiceRevenue         float64 `protobuf:"fixed64,6,opt,name=service_revenue,json=serviceRevenue,proto3" json:"service_revenue,omitempty"`
	OtherRevenue           float64 `protobuf:"fixed64,7,opt,name=other_revenue,json=otherRevenue,proto3" json:"other_revenue,omitempty"`
	TotalExpenses          float64 `protobuf:"fixed64,8,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	CostOfGoodsSold        float64 `protobuf:"fixed64,9,opt,name=cost_of_goods_sold,json=costOfGoodsSold,proto3" json:"cost_of_goods_sold,omitempty"`
	OperatingExpenses      float64 `protobuf:"fixed64,10,opt,name=operating_expenses,json=operatingExpenses,proto3" json:"operating_expenses,omitempty"`
	AdministrativeExpenses float64 `protobuf:"fixed64,11,opt,name=administrative_expenses,json=administrativeExpenses,proto3" json:"administrative_expenses,omitempty"`
	FinancialExpenses      float64 `protobuf:"fixed64,12,opt,name=financial_expenses,json=financialExpenses,proto3" json:"financial_expenses,omitempty"`
	OtherExpenses          float64 `protobuf:"fixed64,13,opt,name=other_expenses,json=otherExpenses,proto3" json:"other_expenses,omitempty"`
	GrossProfit            float64 `protobuf:"fixed64,14,opt,name=gross_profit,json=grossProfit,proto3" json:"gross_profit,omitempty"`
	OperatingProfit        float64 `protobuf:"fixed64,15,opt,name=operating_profit,json=operatingProfit,proto3" json:"operating_profit,omitempty"`
	NetProfit              float64 `protobuf:"fixed64,16,opt,name=net_profit,json=netProfit,proto3" json:"net_profit,omitempty"`
	CalculatedAt           string  `protobuf:"bytes,17,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	IsFinalized            bool    `protobuf:"varint,18,opt,name=is_finalized,json=isFinalized,proto3" json:"is_finalized,omitempty"`
}

func (x *MonthlyProfitLoss) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MonthlyProfitLoss) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MonthlyProfitLoss) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *MonthlyProfitLoss) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *MonthlyProfitLoss) GetSalesRevenue() float64 {
	if x != nil {
		return x.SalesRevenue
	}
	return 0
}

func (x *MonthlyProfitLoss) GetServiceRevenue() float64 {
	if x != nil {
		return x.ServiceRevenue
	}
	return 0
}

func (x *MonthlyProfitLoss) GetOtherRevenue() float64 {
	if x != nil {
		return x.OtherRevenue
	}
	return 0
}

func (x *MonthlyProfitLoss) GetTotalExpenses() float64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *MonthlyProfitLoss) GetCostOfGoodsSold() float64 {
	if x != nil {
		return x.CostOfGoodsSold
	}
	return 0
}

func (x *MonthlyProfitLoss) GetOperatingExpenses() float64 {
	if x != nil {
		return x.OperatingExpenses
	}
	return 0
}

func (x *MonthlyProfitLoss) GetAdministrativeExpenses() float64 {
	if x != nil {
		return x.AdministrativeExpenses
	}
	return 0
}

func (x *MonthlyProfitLoss) GetFinancialExpenses() float64 {
	if x != nil {
		return x.FinancialExpenses
	}
	return 0
}

func (x *MonthlyProfitLoss) GetOtherExpenses() float64 {
	if x != nil {
		return x.OtherExpenses
	}
	return 0
}

func (x *MonthlyProfitLoss) GetGrossProfit() float64 {
	if x != nil {
		return x.GrossProfit
	}
	return 0
}

func (x *MonthlyProfitLoss) GetOperatingProfit() float64 {
	if x != nil {
		return x.OperatingProfit
	}
	return 0
}

func (x *MonthlyProfitLoss) GetNetProfit() float64 {
	if x != nil {
		return x.NetProfit
	}
	return 0
}

func (x *MonthlyProfitLoss) GetCalculatedAt() string {
	if x != nil {
		return x.CalculatedAt
	}
	return ""
}

func (x *MonthlyProfitLoss) GetIsFinalized() bool {
	if x != nil {
		return x.IsFinalized
	}
	return false
}