// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/finance.proto

package finance_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// FinanceServiceClient is the client API for FinanceService service.
type FinanceServiceClient interface {
	// 获取月度损益表
	GetMonthlyProfitLoss(ctx context.Context, in *GetMonthlyProfitLossRequest, opts ...grpc.CallOption) (*GetMonthlyProfitLossResponse, error)
}

type financeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceServiceClient(cc grpc.ClientConnInterface) FinanceServiceClient {
	return &financeServiceClient{cc}
}

func (c *financeServiceClient) GetMonthlyProfitLoss(ctx context.Context, in *GetMonthlyProfitLossRequest, opts ...grpc.CallOption) (*GetMonthlyProfitLossResponse, error) {
	out := new(GetMonthlyProfitLossResponse)
	err := c.cc.Invoke(ctx, "/finance.v1.FinanceService/GetMonthlyProfitLoss", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceServiceServer is the server API for FinanceService service.
type FinanceServiceServer interface {
	// 获取月度损益表
	GetMonthlyProfitLoss(context.Context, *GetMonthlyProfitLossRequest) (*GetMonthlyProfitLossResponse, error)
	mustEmbedUnimplementedFinanceServiceServer()
}

// UnimplementedFinanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFinanceServiceServer struct {
}

func (UnimplementedFinanceServiceServer) GetMonthlyProfitLoss(context.Context, *GetMonthlyProfitLossRequest) (*GetMonthlyProfitLossResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyProfitLoss not implemented")
}
func (UnimplementedFinanceServiceServer) mustEmbedUnimplementedFinanceServiceServer() {}

// UnsafeFinanceServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeFinanceServiceServer interface {
	mustEmbedUnimplementedFinanceServiceServer()
}

func RegisterFinanceServiceServer(s grpc.ServiceRegistrar, srv FinanceServiceServer) {
	s.RegisterService(&FinanceService_ServiceDesc, srv)
}

func _FinanceService_GetMonthlyProfitLoss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyProfitLossRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetMonthlyProfitLoss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance.v1.FinanceService/GetMonthlyProfitLoss",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetMonthlyProfitLoss(ctx, req.(*GetMonthlyProfitLossRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinanceService_ServiceDesc is the grpc.ServiceDesc for FinanceService service.
var FinanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finance.v1.FinanceService",
	HandlerType: (*FinanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthlyProfitLoss",
			Handler:    _FinanceService_GetMonthlyProfitLoss_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/finance.proto",
}