"""
Built-in organization templates

Provides three pre-built organization structure templates that can be installed
into data/org_templates/ via OrgManager.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Template definitions
# ---------------------------------------------------------------------------

STARTUP_COMPANY: dict = {
    "name": "Startup Company",
    "description": "Standard startup company structure with four departments: engineering, product, marketing, and administration",
    "icon": "🏢",
    "tags": ["company", "startup"],
    "user_persona": {"title": "Chairman", "display_name": "Chairman", "description": "Top decision maker of the company"},
    "core_business": "",
    "heartbeat_enabled": False,
    "heartbeat_interval_s": 1800,
    "heartbeat_prompt": "Review current company operations, identify urgent matters and blockers, and decide whether to assign new tasks or adjust priorities.",
    "standup_enabled": False,
    "standup_cron": "0 9 * * 1-5",
    "standup_agenda": "Each department lead reports yesterday's progress, today's plans, and any blockers.",
    "allow_cross_level": False,
    "max_delegation_depth": 4,
    "conflict_resolution": "manager",
    "scaling_enabled": True,
    "max_nodes": 25,
    "scaling_approval": "user",
    "nodes": [
        {
            "id": "ceo",
            "role_title": "CEO / Chief Executive Officer",
            "role_goal": "Set the company's strategic direction, coordinate departments, and ensure company goals are achieved",
            "role_backstory": "Experienced entrepreneur skilled in strategic planning and team management",
            "agent_source": "local",
            "position": {"x": 400, "y": 0},
            "level": 0,
            "department": "Management",
            "avatar": "ceo",
            "external_tools": ["research", "planning", "memory"],
        },
        {
            "id": "cto",
            "role_title": "CTO / Chief Technology Officer",
            "role_goal": "Ensure a sound technical architecture, maintain code quality, and keep the engineering team running efficiently",
            "role_backstory": "Technical lead with 10 years of full-stack development experience, skilled in architecture design and technology selection",
            "agent_source": "local",
            "position": {"x": 100, "y": 150},
            "level": 1,
            "department": "Engineering",
            "avatar": "cto",
            "external_tools": ["research", "planning", "filesystem", "memory"],
        },
        {
            "id": "architect",
            "role_title": "Architect",
            "role_goal": "Design and maintain system architecture, and establish technical standards",
            "role_backstory": "Senior architect well-versed in distributed systems and microservices",
            "agent_source": "local",
            "position": {"x": 0, "y": 300},
            "level": 2,
            "department": "Engineering",
            "avatar": "architect",
            "external_tools": ["research", "filesystem", "memory"],
        },
        {
            "id": "dev-a",
            "role_title": "Full-Stack Engineer A",
            "role_goal": "Deliver assigned development tasks with high quality",
            "role_backstory": "Full-stack developer with extensive experience on both frontend and backend",
            "agent_source": "local",
            "position": {"x": 100, "y": 300},
            "level": 2,
            "department": "Engineering",
            "avatar": "dev-m",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "dev-b",
            "role_title": "Full-Stack Engineer B",
            "role_goal": "Deliver assigned development tasks with high quality",
            "role_backstory": "Full-stack developer skilled in performance optimization and testing",
            "agent_source": "local",
            "position": {"x": 200, "y": 300},
            "level": 2,
            "department": "Engineering",
            "avatar": "dev-f",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "devops",
            "role_title": "DevOps Engineer",
            "role_goal": "Ensure stable service operation with automated deployment and monitoring",
            "role_backstory": "DevOps engineer proficient in CI/CD, containerization, and cloud services",
            "agent_source": "local",
            "position": {"x": 300, "y": 300},
            "level": 2,
            "department": "Engineering",
            "avatar": "devops",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "cpo",
            "role_title": "CPO / Chief Product Officer",
            "role_goal": "Define product roadmap, ensure the right product direction, and deliver a great user experience",
            "role_backstory": "Product expert skilled in user needs analysis and product planning",
            "agent_source": "local",
            "position": {"x": 400, "y": 150},
            "level": 1,
            "department": "Product",
            "avatar": "cpo",
            "external_tools": ["research", "planning", "memory"],
        },
        {
            "id": "pm",
            "role_title": "Product Manager",
            "role_goal": "Manage requirements, scheduling, and project progress",
            "role_backstory": "Experienced product manager skilled in requirements analysis and project management",
            "agent_source": "local",
            "position": {"x": 350, "y": 300},
            "level": 2,
            "department": "Product",
            "avatar": "pm",
            "external_tools": ["research", "planning", "memory"],
        },
        {
            "id": "ui-designer",
            "role_title": "UI Designer",
            "role_goal": "Design beautiful and user-friendly interfaces",
            "role_backstory": "UI/UX designer skilled in interaction design and visual design",
            "agent_source": "local",
            "position": {"x": 450, "y": 300},
            "level": 2,
            "department": "Product",
            "avatar": "designer-f",
            "external_tools": ["browser", "filesystem"],
        },
        {
            "id": "cmo",
            "role_title": "CMO / Chief Marketing Officer",
            "role_goal": "Define marketing strategy, grow brand awareness, and drive user growth",
            "role_backstory": "Marketing expert skilled in brand strategy and growth hacking",
            "agent_source": "local",
            "position": {"x": 600, "y": 150},
            "level": 1,
            "department": "Marketing",
            "avatar": "cmo",
            "external_tools": ["research", "planning", "memory"],
        },
        {
            "id": "content-op",
            "role_title": "Content Operations",
            "role_goal": "Produce high-quality content and maintain a consistent publishing cadence",
            "role_backstory": "Content creator skilled in copywriting and content planning",
            "agent_source": "local",
            "position": {"x": 550, "y": 300},
            "level": 2,
            "department": "Marketing",
            "avatar": "writer",
            "external_tools": ["research", "filesystem", "memory"],
        },
        {
            "id": "seo",
            "role_title": "SEO Specialist",
            "role_goal": "Improve search engine rankings and grow organic traffic",
            "role_backstory": "SEO expert proficient in search engine optimization strategies",
            "agent_source": "local",
            "position": {"x": 650, "y": 300},
            "level": 2,
            "department": "Marketing",
            "avatar": "researcher",
            "external_tools": ["research", "memory"],
        },
        {
            "id": "social-media",
            "role_title": "Social Media Manager",
            "role_goal": "Manage social media accounts and grow social influence",
            "role_backstory": "Social media operations expert skilled in community management and engagement",
            "agent_source": "local",
            "position": {"x": 750, "y": 300},
            "level": 2,
            "department": "Marketing",
            "avatar": "media",
            "external_tools": ["research", "memory"],
        },
        {
            "id": "cfo",
            "role_title": "CFO / Chief Financial Officer",
            "role_goal": "Manage company finances, control costs, and keep funding healthy",
            "role_backstory": "Financial management expert skilled in budgeting and financial analysis",
            "agent_source": "local",
            "position": {"x": 800, "y": 150},
            "level": 1,
            "department": "Administration",
            "avatar": "cfo",
            "external_tools": ["research", "memory"],
        },
        {
            "id": "hr",
            "role_title": "HR / Human Resources",
            "role_goal": "Manage team building and talent development",
            "role_backstory": "HR expert skilled in recruiting and team culture building",
            "agent_source": "local",
            "position": {"x": 850, "y": 300},
            "level": 2,
            "department": "Administration",
            "avatar": "hr",
            "external_tools": ["research", "memory"],
        },
        {
            "id": "legal",
            "role_title": "Legal Counsel",
            "role_goal": "Provide legal advice and ensure the company operates in compliance",
            "role_backstory": "Legal counsel proficient in business law and compliance matters",
            "agent_source": "local",
            "position": {"x": 950, "y": 300},
            "level": 2,
            "department": "Administration",
            "avatar": "legal",
            "external_tools": ["research", "memory"],
        },
    ],
    "edges": [
        {
            "id": "e-ceo-cto",
            "source": "ceo",
            "target": "cto",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-ceo-cpo",
            "source": "ceo",
            "target": "cpo",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-ceo-cmo",
            "source": "ceo",
            "target": "cmo",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-ceo-cfo",
            "source": "ceo",
            "target": "cfo",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-cto-arch",
            "source": "cto",
            "target": "architect",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-cto-deva",
            "source": "cto",
            "target": "dev-a",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-cto-devb",
            "source": "cto",
            "target": "dev-b",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-cto-devops",
            "source": "cto",
            "target": "devops",
            "edge_type": "hierarchy",
            "label": "",
        },
        {"id": "e-cpo-pm", "source": "cpo", "target": "pm", "edge_type": "hierarchy", "label": ""},
        {
            "id": "e-cpo-ui",
            "source": "cpo",
            "target": "ui-designer",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-cmo-content",
            "source": "cmo",
            "target": "content-op",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-cmo-seo",
            "source": "cmo",
            "target": "seo",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-cmo-social",
            "source": "cmo",
            "target": "social-media",
            "edge_type": "hierarchy",
            "label": "",
        },
        {"id": "e-cfo-hr", "source": "cfo", "target": "hr", "edge_type": "hierarchy", "label": ""},
        {
            "id": "e-cfo-legal",
            "source": "cfo",
            "target": "legal",
            "edge_type": "hierarchy",
            "label": "",
        },
        {
            "id": "e-cpo-cto",
            "source": "cpo",
            "target": "cto",
            "edge_type": "collaborate",
            "label": "Product-engineering alignment",
        },
        {
            "id": "e-pm-deva",
            "source": "pm",
            "target": "dev-a",
            "edge_type": "collaborate",
            "label": "Requirements discussion",
        },
        {
            "id": "e-pm-devb",
            "source": "pm",
            "target": "dev-b",
            "edge_type": "collaborate",
            "label": "Requirements discussion",
        },
        {
            "id": "e-content-seo",
            "source": "content-op",
            "target": "seo",
            "edge_type": "collaborate",
            "label": "Content optimization",
        },
    ],
}

SOFTWARE_TEAM: dict = {
    "name": "Software Engineering Team",
    "description": "Software development team split into frontend and backend groups, with QA, DevOps, and technical writing",
    "icon": "💻",
    "tags": ["software", "engineering"],
    "user_persona": {
        "title": "Product Owner",
        "display_name": "Product Owner",
        "description": "Requester and final acceptance authority for the project",
    },
    "heartbeat_enabled": False,
    "heartbeat_interval_s": 3600,
    "heartbeat_prompt": "Check project progress and technical blockers, and coordinate frontend and backend work.",
    "allow_cross_level": True,
    "max_delegation_depth": 3,
    "conflict_resolution": "manager",
    "scaling_enabled": True,
    "max_nodes": 15,
    "scaling_approval": "manager",
    "nodes": [
        {
            "id": "tech-lead",
            "role_title": "Tech Lead",
            "role_goal": "Steer technical direction, coordinate frontend and backend, and ensure the project is delivered on time",
            "role_backstory": "Senior tech lead with strong full-stack skills, good at making technical decisions",
            "agent_source": "local",
            "position": {"x": 300, "y": 0},
            "level": 0,
            "department": "Engineering",
            "avatar": "cto",
            "external_tools": ["research", "planning", "filesystem", "memory"],
        },
        {
            "id": "fe-lead",
            "role_title": "Frontend Lead",
            "role_goal": "Manage frontend development progress and quality",
            "role_backstory": "Frontend technical expert proficient in React/Vue",
            "agent_source": "local",
            "position": {"x": 100, "y": 150},
            "level": 1,
            "department": "Frontend",
            "avatar": "dev-m",
            "external_tools": ["research", "planning", "filesystem", "memory"],
        },
        {
            "id": "fe-dev-a",
            "role_title": "Frontend Developer A",
            "role_goal": "Implement frontend features",
            "role_backstory": "Frontend developer",
            "agent_source": "local",
            "position": {"x": 50, "y": 300},
            "level": 2,
            "department": "Frontend",
            "avatar": "dev-f",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "fe-dev-b",
            "role_title": "Frontend Developer B",
            "role_goal": "Implement frontend features",
            "role_backstory": "Frontend developer",
            "agent_source": "local",
            "position": {"x": 150, "y": 300},
            "level": 2,
            "department": "Frontend",
            "avatar": "dev-m",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "be-lead",
            "role_title": "Backend Lead",
            "role_goal": "Manage backend development progress and quality",
            "role_backstory": "Backend technical expert proficient in Python/Go",
            "agent_source": "local",
            "position": {"x": 350, "y": 150},
            "level": 1,
            "department": "Backend",
            "avatar": "dev-f",
            "external_tools": ["research", "planning", "filesystem", "memory"],
        },
        {
            "id": "be-dev-a",
            "role_title": "Backend Developer A",
            "role_goal": "Implement backend features",
            "role_backstory": "Backend developer",
            "agent_source": "local",
            "position": {"x": 300, "y": 300},
            "level": 2,
            "department": "Backend",
            "avatar": "dev-m",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "be-dev-b",
            "role_title": "Backend Developer B",
            "role_goal": "Implement backend features",
            "role_backstory": "Backend developer",
            "agent_source": "local",
            "position": {"x": 400, "y": 300},
            "level": 2,
            "department": "Backend",
            "avatar": "dev-f",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "qa",
            "role_title": "QA Engineer",
            "role_goal": "Ensure software quality by writing and executing tests",
            "role_backstory": "Testing expert skilled in test automation",
            "agent_source": "local",
            "position": {"x": 500, "y": 150},
            "level": 1,
            "department": "Engineering",
            "avatar": "researcher",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "devops-eng",
            "role_title": "DevOps Engineer",
            "role_goal": "Maintain CI/CD pipelines and production environments",
            "role_backstory": "DevOps engineer",
            "agent_source": "local",
            "position": {"x": 500, "y": 300},
            "level": 2,
            "department": "Engineering",
            "avatar": "devops",
            "external_tools": ["filesystem", "memory"],
        },
        {
            "id": "tech-writer",
            "role_title": "Technical Writer",
            "role_goal": "Write and maintain technical documentation",
            "role_backstory": "Technical writing expert",
            "agent_source": "local",
            "position": {"x": 600, "y": 300},
            "level": 2,
            "department": "Engineering",
            "avatar": "writer",
            "external_tools": ["research", "filesystem", "memory"],
        },
    ],
    "edges": [
        {"id": "e1", "source": "tech-lead", "target": "fe-lead", "edge_type": "hierarchy"},
        {"id": "e2", "source": "tech-lead", "target": "be-lead", "edge_type": "hierarchy"},
        {"id": "e3", "source": "tech-lead", "target": "qa", "edge_type": "hierarchy"},
        {"id": "e4", "source": "fe-lead", "target": "fe-dev-a", "edge_type": "hierarchy"},
        {"id": "e5", "source": "fe-lead", "target": "fe-dev-b", "edge_type": "hierarchy"},
        {"id": "e6", "source": "be-lead", "target": "be-dev-a", "edge_type": "hierarchy"},
        {"id": "e7", "source": "be-lead", "target": "be-dev-b", "edge_type": "hierarchy"},
        {"id": "e8", "source": "tech-lead", "target": "devops-eng", "edge_type": "hierarchy"},
        {"id": "e9", "source": "tech-lead", "target": "tech-writer", "edge_type": "hierarchy"},
        {
            "id": "e10",
            "source": "fe-lead",
            "target": "be-lead",
            "edge_type": "collaborate",
            "label": "API integration",
        },
        {
            "id": "e11",
            "source": "qa",
            "target": "fe-lead",
            "edge_type": "consult",
            "label": "Test feedback",
        },
        {
            "id": "e12",
            "source": "qa",
            "target": "be-lead",
            "edge_type": "consult",
            "label": "Test feedback",
        },
        {
            "id": "e13",
            "source": "devops-eng",
            "target": "fe-lead",
            "edge_type": "collaborate",
            "label": "Deployment coordination",
        },
        {
            "id": "e14",
            "source": "devops-eng",
            "target": "be-lead",
            "edge_type": "collaborate",
            "label": "Deployment coordination",
        },
    ],
}

CONTENT_OPS: dict = {
    "name": "Content Operations Team",
    "description": "Content creation and operations team led by an editor-in-chief",
    "icon": "📝",
    "tags": ["content", "marketing"],
    "user_persona": {"title": "Producer", "display_name": "Producer", "description": "Decision maker for content direction"},
    "heartbeat_enabled": False,
    "heartbeat_interval_s": 3600,
    "heartbeat_prompt": "Review content publishing schedule and performance metrics, and adjust content strategy.",
    "allow_cross_level": True,
    "max_delegation_depth": 2,
    "conflict_resolution": "manager",
    "scaling_enabled": True,
    "max_nodes": 10,
    "scaling_approval": "manager",
    "nodes": [
        {
            "id": "editor-in-chief",
            "role_title": "Editor-in-Chief",
            "role_goal": "Define content strategy, review published content, and ensure content quality",
            "role_backstory": "Senior editor-in-chief skilled in content strategy and team management",
            "agent_source": "local",
            "position": {"x": 300, "y": 0},
            "level": 0,
            "department": "Editorial",
            "avatar": "ceo",
            "external_tools": ["research", "planning", "memory"],
        },
        {
            "id": "planner",
            "role_title": "Content Planner",
            "role_goal": "Plan topics and manage content schedule",
            "role_backstory": "Content planning expert skilled in spotting trends and planning topics",
            "agent_source": "local",
            "position": {"x": 100, "y": 150},
            "level": 1,
            "department": "Editorial",
            "avatar": "pm",
            "external_tools": ["research", "planning", "memory"],
        },
        {
            "id": "writer-a",
            "role_title": "Copywriter A",
            "role_goal": "Produce high-quality copy",
            "role_backstory": "Senior copywriter skilled in long-form deep-dive articles",
            "agent_source": "local",
            "position": {"x": 50, "y": 300},
            "level": 2,
            "department": "Creative",
            "avatar": "writer",
            "external_tools": ["research", "filesystem", "memory"],
        },
        {
            "id": "writer-b",
            "role_title": "Copywriter B",
            "role_goal": "Produce high-quality copy",
            "role_backstory": "Creative copywriter skilled in short-form and social media copy",
            "agent_source": "local",
            "position": {"x": 150, "y": 300},
            "level": 2,
            "department": "Creative",
            "avatar": "media",
            "external_tools": ["research", "filesystem", "memory"],
        },
        {
            "id": "seo-opt",
            "role_title": "SEO Optimizer",
            "role_goal": "Optimize content for search engine performance",
            "role_backstory": "SEO expert",
            "agent_source": "local",
            "position": {"x": 300, "y": 150},
            "level": 1,
            "department": "Operations",
            "avatar": "researcher",
            "external_tools": ["research", "memory"],
        },
        {
            "id": "visual",
            "role_title": "Visual Designer",
            "role_goal": "Design images and visual assets",
            "role_backstory": "Visual designer",
            "agent_source": "local",
            "position": {"x": 400, "y": 300},
            "level": 2,
            "department": "Creative",
            "avatar": "designer-f",
            "external_tools": ["browser", "filesystem"],
        },
        {
            "id": "data-analyst",
            "role_title": "Data Analyst",
            "role_goal": "Analyze content metrics and provide data-driven topic suggestions",
            "role_backstory": "Data analyst",
            "agent_source": "local",
            "position": {"x": 500, "y": 150},
            "level": 1,
            "department": "Operations",
            "avatar": "analyst",
            "external_tools": ["research", "memory"],
        },
    ],
    "edges": [
        {"id": "e1", "source": "editor-in-chief", "target": "planner", "edge_type": "hierarchy"},
        {"id": "e2", "source": "editor-in-chief", "target": "seo-opt", "edge_type": "hierarchy"},
        {
            "id": "e3",
            "source": "editor-in-chief",
            "target": "data-analyst",
            "edge_type": "hierarchy",
        },
        {"id": "e4", "source": "planner", "target": "writer-a", "edge_type": "hierarchy"},
        {"id": "e5", "source": "planner", "target": "writer-b", "edge_type": "hierarchy"},
        {"id": "e6", "source": "planner", "target": "visual", "edge_type": "hierarchy"},
        {
            "id": "e7",
            "source": "writer-a",
            "target": "seo-opt",
            "edge_type": "collaborate",
            "label": "Content optimization",
        },
        {
            "id": "e8",
            "source": "writer-b",
            "target": "seo-opt",
            "edge_type": "collaborate",
            "label": "Content optimization",
        },
        {
            "id": "e9",
            "source": "writer-a",
            "target": "visual",
            "edge_type": "collaborate",
            "label": "Image coordination",
        },
        {
            "id": "e10",
            "source": "writer-b",
            "target": "visual",
            "edge_type": "collaborate",
            "label": "Image coordination",
        },
        {
            "id": "e11",
            "source": "data-analyst",
            "target": "planner",
            "edge_type": "collaborate",
            "label": "Data-driven topic selection",
        },
    ],
}

ALL_TEMPLATES: dict[str, dict] = {
    "startup-company": STARTUP_COMPANY,
    "software-team": SOFTWARE_TEAM,
    "content-ops": CONTENT_OPS,
}


TEMPLATE_POLICY_MAP: dict[str, str] = {
    "startup-company": "default",
    "software-team": "software-team",
    "content-ops": "content-ops",
}


def _auto_assign_avatars(tpl_data: dict) -> None:
    """Fill missing avatar fields on template nodes using role-based matching."""
    from openakita.orgs.tool_categories import get_avatar_for_role

    for node in tpl_data.get("nodes", []):
        if not node.get("avatar"):
            node["avatar"] = get_avatar_for_role(node.get("role_title", ""))


def ensure_builtin_templates(templates_dir: Path) -> None:
    """Install built-in templates if they don't exist."""
    templates_dir.mkdir(parents=True, exist_ok=True)
    for tid, tpl in ALL_TEMPLATES.items():
        p = templates_dir / f"{tid}.json"
        if not p.exists():
            tpl_data = dict(tpl)
            tpl_data["policy_template"] = TEMPLATE_POLICY_MAP.get(tid, "default")
            _auto_assign_avatars(tpl_data)
            p.write_text(json.dumps(tpl_data, ensure_ascii=False, indent=2), encoding="utf-8")
            logger.info(f"[Templates] Installed built-in template: {tid}")
